---
# tasks file for jboss-eap-standalone
- name: Install java and some basic dependencies
  yum:
    name: java-11-openjdk-devel
    state: latest
  with_items:
    - java-11-openjdk-devel
    - python3

- name: Copy jboss-eap installer zip
  copy:
    src: jboss-eap-7.2.0.zip
    dest: /tmp
  
- name: Add the group "jboss-eap"
  group: 
    name: jboss-eap

- name: Add the user 'jboss-eap'
  user:
    name: jboss-eap
    comment: service user for jboss-eap
    shell: /usr/bin/sh
    group: jboss-eap
    create_home: no

- name: Extract archive
  unarchive:
    creates: /opt/jboss-eap/
    src: /tmp/jboss-eap-7.2.0.zip
    dest: /opt/
    remote_src: yes
    mode: 0655
    owner: jboss-eap
    group: jboss-eap

- name: Copy standalone.xml configuration file
  template:
    src: standalone.xml
    dest: /opt/jboss-eap/standalone/configuration/
  notify: restart jboss


- name: Copy jboss-eap service file
  template:
    src: jboss-eap-as-standalone.service.j2
    dest: /etc/systemd/system/jboss-eap-as-standalone.service
    mode: 0750
    owner: "{{ jboss.user }}"
    group: "{{ jboss.group }}"
  notify: 
    - enable jboss-eap service
    -  restart jboss


- name: Create the /var/run/jboss-eap directory and set the jboss-eap user as the owner
  file:
    path: /var/run/jboss-eap
    state: directory
    mode: '0755'
    owner: jboss-eap
  notify: 
    - enable jboss-eap service
    - restart jboss

- name: start jboss 
  systemd: 
    name: jboss-eap-as-standalone.service
    state: started
    daemon_reload: yes


- name: Ensure that firewalld is installed
  yum:
    name: firewalld
    state: present

- name: Ensure that firewalld is started
  service:
    name: firewalld
    state: started

- name: deploy firewalld rules
  firewalld:
    immediate: yes
    port: "{{ item }}"
    state: enabled
    permanent: yes
  with_items:
  - "{{ http_port }}/tcp"
  - "{{ https_port }}/tcp"
  - "9990/tcp"